fastlane_version '2.157'
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
      xcversion(version: "13.2.1")
      run_tests(scheme: "WonderfulPalette")
    end
end